development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["PHOTOBLOG_TEST_DB"] %>
  pool: 5
  username: <%= ENV["PG_USERNAME"] %>

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["PHOTOBLOG_PROD_DB"] %>
  pool: 5
  username: <%= ENV["PG_USERNAME"] %>
